name: My First GitHub Actions

on: [push]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13.0-beta.2"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
